id: tz.ig
packageId: tz.ig
canonical: https://build.fhir.org/ig/Speedykom/tz-fhir-ig
url: https://build.fhir.org/ig/Speedykom/tz-fhir-ig/ImplementationGuide/tz.ig

name: TanzaniaNationalFHIRIG
title: "Tanzania National FHIR Implementation Guide"

description: |
  The official FHIR R5 Implementation Guide for Tanzania, including Logical Models,
  StructureMaps, ConceptMaps, terminology assets, examples, and national profiles.
  This IG supports national interoperability and legacy system transformation.

version: 0.1.0
status: active
license: CC0-1.0
fhirVersion: 5.0.0
releaseLabel: ci-build

publisher:
  name: Ministry of Health â€“ Tanzania
  url: https://moh.go.tz

contact:
  - name: Tanzania Digital Health Team
    telecom:
      - system: email
        value: hie@moh.go.tz
        use: work

jurisdiction: urn:iso:std:iso:3166#TZ "Tanzania"

dependencies:
  hl7.fhir.r5.core: 5.0.0

parameters:
  excludettl: true
  validation: [ no-broken-links ]

FSHOnly: false