id: tz-fhir-ig
packageId: tz.fhir.ig
canonical: http://moh.tz/fhir
url: http://moh.tz/fhir/ImplementationGuide/tz-fhir-ig
name: TanzaniaNationalFHIRIG
title: "Tanzania FHIR Facade Implementation Guide"

description: >
  The national FHIR R5 Implementation Guide for Tanzania,
  including Logical Models, StructureMaps, ConceptMaps,
  terminology assets, and transformation rules.

status: active
version: 0.1.0
fhirVersion: 5.0.0

# REQUIRED BY SUSHI
copyrightYear: 2025+
releaseLabel: ci-build

license: CC0-1.0

publisher:
  name: Ministry of Health â€“ Tanzania
  url: https://moh.go.tz
  email: info@moh.go.tz

contact:
  - name: Tanzania Digital Health Team
    telecom:
      - system: email
        value: contact@speedykom.org
        use: work

jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#834 "Tanzania"

dependencies:
  hl7.fhir.r5.core: 5.0.0
  hl7.terminology.r5: 7.0.0

FSHOnly: false

pages:
  index.md: Home
